"""atulizado o modelo auth

Revision ID: 2e867277b2d1
Revises: 0b76da3fc1d0
Create Date: 2022-10-17 19:51:08.048189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e867277b2d1'
down_revision = '0b76da3fc1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'role_users', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'role_users', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_users', type_='foreignkey')
    op.drop_constraint(None, 'role_users', type_='foreignkey')
    # ### end Alembic commands ###
