"""alteração da Ordem_servico.solicitante_id para nullable=True

Revision ID: 4f13cd62946c
Revises: f3a27979cacc
Create Date: 2023-07-08 12:19:52.928129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f13cd62946c'
down_revision = 'f3a27979cacc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'empresa', 'tipo_empresa', ['tipoempresa_id'], ['id'])
    op.create_foreign_key(None, 'empresa', 'contrato', ['contrato_id'], ['id'])
    op.create_foreign_key(None, 'equipamento', 'subgrupo', ['subgrupo_id'], ['id'])
    op.create_foreign_key(None, 'grupo', 'empresa', ['empresa_id'], ['id'])
    op.alter_column('ordem_servico', 'solicitante_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'ordem_servico', 'equipamento', ['equipamento_id'], ['id'])
    op.create_foreign_key(None, 'ordem_servico', 'tipo_ordem', ['tipoordem_id'], ['id'])
    op.create_foreign_key(None, 'ordem_servico', 'usuario', ['solicitante_id'], ['id'])
    op.create_foreign_key(None, 'ordem_servico', 'situacao_ordem', ['situacaoordem_id'], ['id'])
    op.create_foreign_key(None, 'perfil', 'empresa', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'periodicidade', 'unidade', ['unidade_id'], ['id'])
    op.create_foreign_key(None, 'plano_manutencao', 'equipamento', ['equipamento_id'], ['id'])
    op.create_foreign_key(None, 'plano_manutencao', 'tipo_ordem', ['tipoordem_id'], ['id'])
    op.create_foreign_key(None, 'plano_manutencao', 'periodicidade', ['periodicidade_id'], ['id'])
    op.create_foreign_key(None, 'plano_manutencao', 'tipo_data', ['tipodata_id'], ['id'])
    op.create_foreign_key(None, 'subgrupo', 'grupo', ['grupo_id'], ['id'])
    op.create_foreign_key(None, 'supplier', 'empresa', ['company_id'], ['id'])
    op.create_foreign_key(None, 'tela_contrato', 'tela', ['tela_id'], ['id'])
    op.create_foreign_key(None, 'tela_contrato', 'contrato', ['contrato_id'], ['id'])
    op.create_foreign_key(None, 'tela_perfil', 'perfil', ['perfil_id'], ['id'])
    op.create_foreign_key(None, 'tela_perfil', 'tela', ['tela_id'], ['id'])
    op.create_foreign_key(None, 'tramitacao_ordem', 'situacao_ordem', ['situacaoordem_id'], ['id'])
    op.create_foreign_key(None, 'tramitacao_ordem', 'usuario', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'tramitacao_ordem', 'ordem_servico', ['ordemservico_id'], ['id'])
    op.create_foreign_key(None, 'usuario', 'perfil', ['perfil_id'], ['id'])
    op.create_foreign_key(None, 'usuario', 'empresa', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'usuario', 'senha', ['senha_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_constraint(None, 'tramitacao_ordem', type_='foreignkey')
    op.drop_constraint(None, 'tramitacao_ordem', type_='foreignkey')
    op.drop_constraint(None, 'tramitacao_ordem', type_='foreignkey')
    op.drop_constraint(None, 'tela_perfil', type_='foreignkey')
    op.drop_constraint(None, 'tela_perfil', type_='foreignkey')
    op.drop_constraint(None, 'tela_contrato', type_='foreignkey')
    op.drop_constraint(None, 'tela_contrato', type_='foreignkey')
    op.drop_constraint(None, 'supplier', type_='foreignkey')
    op.drop_constraint(None, 'subgrupo', type_='foreignkey')
    op.drop_constraint(None, 'plano_manutencao', type_='foreignkey')
    op.drop_constraint(None, 'plano_manutencao', type_='foreignkey')
    op.drop_constraint(None, 'plano_manutencao', type_='foreignkey')
    op.drop_constraint(None, 'plano_manutencao', type_='foreignkey')
    op.drop_constraint(None, 'periodicidade', type_='foreignkey')
    op.drop_constraint(None, 'perfil', type_='foreignkey')
    op.drop_constraint(None, 'ordem_servico', type_='foreignkey')
    op.drop_constraint(None, 'ordem_servico', type_='foreignkey')
    op.drop_constraint(None, 'ordem_servico', type_='foreignkey')
    op.drop_constraint(None, 'ordem_servico', type_='foreignkey')
    op.alter_column('ordem_servico', 'solicitante_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'grupo', type_='foreignkey')
    op.drop_constraint(None, 'equipamento', type_='foreignkey')
    op.drop_constraint(None, 'empresa', type_='foreignkey')
    op.drop_constraint(None, 'empresa', type_='foreignkey')
    # ### end Alembic commands ###
