"""inclusão

Revision ID: f3a27979cacc
Revises: 7e6650f925eb
Create Date: 2023-07-08 10:59:53.014343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3a27979cacc'
down_revision = '7e6650f925eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sistema_nome', table_name='sistema')
    op.drop_table('sistema')
    op.create_foreign_key(None, 'empresa', 'tipo_empresa', ['tipoempresa_id'], ['id'])
    op.create_foreign_key(None, 'empresa', 'contrato', ['contrato_id'], ['id'])
    op.create_foreign_key(None, 'equipamento', 'subgrupo', ['subgrupo_id'], ['id'])
    op.create_foreign_key(None, 'grupo', 'empresa', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'ordem_servico', 'situacao_ordem', ['situacaoordem_id'], ['id'])
    op.create_foreign_key(None, 'ordem_servico', 'equipamento', ['equipamento_id'], ['id'])
    op.create_foreign_key(None, 'ordem_servico', 'tipo_ordem', ['tipoordem_id'], ['id'])
    op.create_foreign_key(None, 'ordem_servico', 'usuario', ['solicitante_id'], ['id'])
    op.create_foreign_key(None, 'perfil', 'empresa', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'periodicidade', 'unidade', ['unidade_id'], ['id'])
    op.create_foreign_key(None, 'plano_manutencao', 'equipamento', ['equipamento_id'], ['id'])
    op.create_foreign_key(None, 'plano_manutencao', 'periodicidade', ['periodicidade_id'], ['id'])
    op.create_foreign_key(None, 'plano_manutencao', 'tipo_data', ['tipodata_id'], ['id'])
    op.create_foreign_key(None, 'plano_manutencao', 'tipo_ordem', ['tipoordem_id'], ['id'])
    op.create_foreign_key(None, 'subgrupo', 'grupo', ['grupo_id'], ['id'])
    op.create_foreign_key(None, 'supplier', 'empresa', ['company_id'], ['id'])
    op.create_foreign_key(None, 'tela_contrato', 'contrato', ['contrato_id'], ['id'])
    op.create_foreign_key(None, 'tela_contrato', 'tela', ['tela_id'], ['id'])
    op.create_foreign_key(None, 'tela_perfil', 'perfil', ['perfilacesso_id'], ['id'])
    op.create_foreign_key(None, 'tela_perfil', 'tela', ['tela_id'], ['id'])
    op.create_foreign_key(None, 'tramitacao_ordem', 'ordem_servico', ['ordemservico_id'], ['id'])
    op.create_foreign_key(None, 'tramitacao_ordem', 'situacao_ordem', ['situacaoordem_id'], ['id'])
    op.create_foreign_key(None, 'tramitacao_ordem', 'usuario', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'usuario', 'perfil', ['perfilacesso_id'], ['id'])
    op.create_foreign_key(None, 'usuario', 'empresa', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'usuario', 'senha', ['senha_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_constraint(None, 'tramitacao_ordem', type_='foreignkey')
    op.drop_constraint(None, 'tramitacao_ordem', type_='foreignkey')
    op.drop_constraint(None, 'tramitacao_ordem', type_='foreignkey')
    op.drop_constraint(None, 'tela_perfil', type_='foreignkey')
    op.drop_constraint(None, 'tela_perfil', type_='foreignkey')
    op.drop_constraint(None, 'tela_contrato', type_='foreignkey')
    op.drop_constraint(None, 'tela_contrato', type_='foreignkey')
    op.drop_constraint(None, 'supplier', type_='foreignkey')
    op.drop_constraint(None, 'subgrupo', type_='foreignkey')
    op.drop_constraint(None, 'plano_manutencao', type_='foreignkey')
    op.drop_constraint(None, 'plano_manutencao', type_='foreignkey')
    op.drop_constraint(None, 'plano_manutencao', type_='foreignkey')
    op.drop_constraint(None, 'plano_manutencao', type_='foreignkey')
    op.drop_constraint(None, 'periodicidade', type_='foreignkey')
    op.drop_constraint(None, 'perfil', type_='foreignkey')
    op.drop_constraint(None, 'ordem_servico', type_='foreignkey')
    op.drop_constraint(None, 'ordem_servico', type_='foreignkey')
    op.drop_constraint(None, 'ordem_servico', type_='foreignkey')
    op.drop_constraint(None, 'ordem_servico', type_='foreignkey')
    op.drop_constraint(None, 'grupo', type_='foreignkey')
    op.drop_constraint(None, 'equipamento', type_='foreignkey')
    op.drop_constraint(None, 'empresa', type_='foreignkey')
    op.drop_constraint(None, 'empresa', type_='foreignkey')
    op.create_table('sistema',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ativo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('equipamento_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index('ix_sistema_nome', 'sistema', ['nome'], unique=False)
    # ### end Alembic commands ###
